name = "spotify"
main = "src/index.ts"
compatibility_date = "2023-08-29"
usage_model = "bundled"
env = { }

routes = [
  { pattern = "worker.vinh.dev/spotify*", zone_name = "vinh.dev" }
]

[triggers]
crons = [ ]
